### ISSUE TITLE
Add to npm. Create package.json

### ISSUE THREAD

**Issue by jimthedev** [webkul/csspin#1]
This looks great. Could you add it to npm so that we don't need bower to get it?

**Comment by webkul-nitish** [comment]
Thanks! @jimthedev for your kind suggestion, We'll be adding this to npm as well.

**Comment by jimthedev** [comment]
Thanks! That is exciting. We're using this in one of my classes right now. Keep up the good work.

**Comment by webkul-nitish** [comment]
Great to hear that! CSSPIN has now also been added as a npm package. Please check README.md for update 📖
