### ISSUE TITLE
i only want to use one loader not all any way possible?

### ISSUE THREAD

**Issue by rafique97** [webkul/csspin#2]
csspin.css is too heavy to include in my project

**Comment by webkul-nitish** [comment]
Of course, If you wish to use only one Spinner/Loader that is possible.
Checkout [Less Files](https://github.com/webkul/csspin/tree/master/less) and [CSS Files](https://github.com/webkul/csspin/tree/master/css) to use individual spinners/loaders.
[Read Doc](https://github.com/webkul/csspin/blob/master/README.md) for more.

**Comment by rafique97** [comment]
ok got it thanks for quick reply
